### ISSUE TITLE
Proposal - enable external CRDs: skipper RouteGroup, FabricGateway

### ISSUE THREAD

**Issue by szuecs** [zalando-incubator/stackset-controller#159]
## Purpose

Enhance stackset to support more objects than Ingress to do traffic switching.

## Problem statement

New CRDs, RouteGroup and FabricGateway, that define HTTP routing, require support from stackset to enable automated traffic switching.

Right now stackset-controller stores desired and actual traffic decisions in the managed Ingress object. It uses `zalando.org/backend-weights` to change skipper's ingress annotation to change actual traffic and  `zalando.org/stack-traffic-weights` to store the desired traffic decision from a client.

A, soon upcoming OpenSource project, the FabricGateway, creates multiple Ingress objects from another enhanced open-api-spec like CRD. To enable traffic switching for this we would need to enable the fabricgateway-controller to create the ingress resources correctly.  The traffic switch annotation `zalando.org/backend-weights` for skipper should be on all Ingress objects created/updated/deleted by fabricgateway. StackSet does not need to know this but enable fabricgateway-controller to set the active annotation `zalando.org/backend-weights` to all the Ingress objects for the CRD.

Another example, [skipper RouteGroup](https://github.com/zalando/skipper/blob/a1579e1cfa7978b4457cd9ea8286ab5096e2d49e/dataclients/kubernetes/crd.md), supports more complex routing via CRD.
To enable [traffic switching for a RouteGroup](https://github.com/zalando/skipper/blob/a1579e1cfa7978b4457cd9ea8286ab5096e2d49e/dataclients/kubernetes/crd.md#traffic-switching) we need to store the desired traffic state somewhere else as in an Ingress annotation, because there might not be an Ingress.

For better usability, it makes sense to have both annotations set to the stackset. It will be possible to support our users and show better results in Kubernetes events. These events would show up in `kubectl describe stackset mystackset`.

There is also the problem, that we can not do input validation for `zalando.org/stack-traffic-weights`, which is set by clients. These clients should be notified, that the input is wrong and report and error to the user.

## Background

For traffic switching we need to make clear responsibilities and identify what stackset-controller creates and how it notifies other controllers. The core of stackset-controller is, that it creates deployment, service and orchestrates the traffic switching via annotation to set per service a weight on the created Ingress object.

Right now stackset-controller also creates an Ingress from a more reduced stackset-Ingress spec.

To understand the details how to enable other controllers we need to understand how they work from traffic point of view.

### FabricGateway

The Fabric Gateway Operator enables support for API Gateway features such as authentication and rate limiting.

In general a fabricgateway spec looks like this:

```
spec:
  paths:
    /api:
      delete:
        x-fabric-privileges:
        - myapp.delete
        x-fabric-ratelimits:
          default-rate: 30
          period: minute
      post:
        x-fabric-privileges:
        - myapp.write
        x-fabric-ratelimits:
          default-rate: 50
          period: minute
...
  x-fabric-admins:
  - someone
...
  x-fabric-service:
  - host: api.example.org
    serviceName: myapp-svc
...
```

As you can see there is also a list of host and service definitions, similar to Ingress.

### RouteGroup

The [RouteGroup proposal](https://github.com/zalando/skipper/blob/a1579e1cfa7978b4457cd9ea8286ab5096e2d49e/dataclients/kubernetes/crd.md#routegroup-proposal) enables users to create complex routes as a group, which was identified as a common case. It wants to enable use skipper features more user friendly and more safe.

In general a RouteGroup spec looks like this:
```
spec:
  hosts:
  - api.example.org
  - api.service.example.net
  backends:
  - name: api-svc
    type: service
    serviceName: myapp-svc
    servicePort: 80
  defaultBackends:
  - backendName: myapp-svc
    # weight: 80
  routes:
  - path: /api/resource
   ...
 ```

The [RouteGroup spec](https://github.com/zalando/skipper/blob/a1579e1cfa7978b4457cd9ea8286ab5096e2d49e/dataclients/kubernetes/crd.md#proposed-solution) has a list of hosts and a list of backend definitions.
The `defaultBackends` list will be applied to all routes, that have no override `backendRef`.

## Proposal

Ingress spec in stackset will be optional to allow other controllers to create the Ingress resources.

### Ingress resource in StackSet

Right now a stackset has a definition to create an ingress and from their derive information about the `backendPort` of the services. We would need to have a definition by the user that defines the `backendPort` without ingress.

Ingress definition in stackset:

```yaml
spec:
  ingress:
    backendPort: 8080
    hosts:
    - example.org
```

To define the backendPort mapping, we need another resource in the spec and define `ingress` as optional:

```yaml
spec:
  externalIngress:
    backendPort: 8080
```

### Desired traffic switching annotation - set by clients

Move the current Ingress annotation `zalando.org/stack-traffic-weights` to the StackSet object (but see the notes about migration).

Current Ingress annotation
```yaml
kind: Ingress
metadata:
  annotations:
    zalando.org/stack-traffic-weights: '{"mysvc-v1":80, "mysvc-v2": 20}'
```

New StackSet spec:
```yaml
apiVersion: zalando.org/v1
kind: StackSet
spec:
  traffic:
  - stackName: mystack-v1
    weight: 80
  - stackName: mystack-v2
    weight: 20
```

The benefits are, that:

- the owner of the traffic switching is clear, stackset-controller
- clients can easily target traffic switching, because they do not need to figure out which Ingress to traffic switch
- user input errors can be reported to the client
- traffic switching desired change can easily create events on the stackset, which is better for the user to debug

### Active traffic switching annotation - read by clients and other controllers

Provider: Object that controls the `zalando.org/backend-weights` read by ingress controllers, like skipper to switch the actual traffic.

Different stackset "providers" require different data to be set in stackset

#### Ingress

Ingress annotation `zalando.org/backend-weights` will be written to stackset and ingress.

ingress annotation won't change:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    zalando.org/backend-weights: '{"mysvc-v1":80, "mysvc-v2": 20}'
```

stackset will get a status field `traffic`, which can be inspected by clients:
```yaml
apiVersion: zalando.org/v1
kind: Stackset
status:
  traffic:
  - stackName: mystack-v1
    serviceName: mysvc-v1
    servicePort: 80
    weight: 80
  - stackName: mystack-v2
    serviceName: mysvc-v2
    servicePort: 80
    weight: 20
```

The `traffic` key in status was chosen to have an atomic change and group the current status.
If there is only one service we can drop the `weight`.

#### Migration

Both configurations will be supported for some time to make the migration a bit less disruptive. Stackset Controller will support reading stack traffic weights from both Ingress resource and Stackset spec. The Ingress resource will have an annotation (`zalando.org/traffic-authoritative`) indicating whether the clients should keep updating the Ingress (if the annotation is missing or `true`) or the Stackset (if the annotation is set to `false`). Note that switching to Stackset managed traffic weights is a one-way thing, so the users shouldn't expect to switch back and forth. Stackset status will always have the actual traffic weights, even if the Ingress is authoritative.

#### External controller CRDs: RouteGroup Fabricgateway

Stackset-Controller will write the status field `traffic`, which can be used by other controllers to reference the services and do the traffic switching:

```yaml
apiVersion: zalando.org/v1
kind: Stackset
status:
  traffic:
  - stackName: mystack-v1
    serviceName: mysvc-v1
    servicePort: 80
    weight: 80
  - stackName: mystack-v2
    serviceName: mysvc-v2
    servicePort: 80
    weight: 20
```

The binding from a Fabricgateway CRD to a stackset without ingress should reference the stackset-crd, such that fabircgateway-controller can read the service and traffic attributes from the stackset object, instead of using the one defined in `x-fabric-service`:

Fabricgateway
```
spec:
   stackset:
       name: mystackset
```
