### ISSUE TITLE
Pass-on annotations to Ingress objects

### ISSUE THREAD

**Issue by linki** [zalando-incubator/stackset-controller#17]
```
apiVersion: zalando.org/v1
kind: StackSet
metadata:
  name: cluster-registry
spec:
  ingress:
    annotations:
      zalando.org/skipper-filter: ...
```

Custom annotations specified by users should be passed-on to the generated Ingress object.

**Comment by mikkeloscar** [comment]
It's a bug if this is not the case. It should happen: https://github.com/zalando-incubator/stackset-controller/blob/30e2ddcd01fd3b13c851a392e1b7ceae1f76b208/controller/ingress.go#L386-L389

**Comment by mikkeloscar** [comment]
Or `annotations` should be under `metadata`:

```yaml
apiVersion: zalando.org/v1
kind: StackSet
metadata:
  name: cluster-registry
spec:
  ingress:
    metadata:
      annotations:
        zalando.org/skipper-filter: ...
```

Since we don't have validation yet (#10) the error is not caught in your example :(

Maybe we want to remove the need for defining the `metadata` key, but it was done this way to make the API more Kubernetes'ish.
