### ISSUE TITLE
metadata from stackset service won't be propagated

### ISSUE THREAD

**Issue by szuecs** [zalando-incubator/stackset-controller#222]
stackset
```yaml
apiVersion: zalando.org/v1
kind: StackSet
metadata:
....
  name: myapp
  namespace: shadow-test
spec:
...
  stackTemplate:
    metadata:
      creationTimestamp: null
    spec:
      replicas: 3
      service:
        metadata:
          annotations:
            zalando.org/api-usage-monitoring-tag: shadow-test   <--- not propagated to service
          creationTimestamp: null
...
```

service:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:    <--- missing
    stackset-controller.zalando.org/stack-generation: "2"
  creationTimestamp: "2020-06-11T16:17:50Z"
  labels:
    application: myapp
    shadow_test_version: dl1
    stack-version: master-9
    stackset: myapp-9
  name: myapp-9
  namespace: shadow-test
```

Code generating the service with annotations: https://github.com/zalando-incubator/stackset-controller/blob/2baddca617e2b76e34976357765206280cfd382e/pkg/core/stack_resources.go#L63-L71
