### ISSUE TITLE
StackSet cannot be created when RouteGroup contains metadata

### ISSUE THREAD

**Issue by amila-ku** [zalando-incubator/stackset-controller#278]
Stackset creation fails when stackset has a routegroup and the routegroup contains a metadata section. This prevents the use of annotations to set loadbalancer specific configurations

```
apiVersion: zalando.org/v1
kind: StackSet
metadata:
  name: my-app-amilak
spec:
  # optional Ingress definition.
  routegroup:
    # optional metadata Ingress definition
    metadata:
       annotations:
          zalando.org/aws-load-balancer-ssl-policy: ELBSecurityPolicy-2016-08
    hosts:
    - testnginx.payments-core-test.zalan.do
    backendPort: 80
    routes:
    - pathSubtree: /
      filters:
      - preserveHost("false")
  stackLifecycle:
    scaledownTTLSeconds: 1800 # TTL for when to scale down the pods of a stack that is not getting traffic. (30 min.)
    limit: 1 # maximum number of scaled down stacks to keep.
             # If there are more than `limit` _extra_ (ones without traffic) stacks, the oldest stacks which are scaled
             # down will be deleted.
  stackTemplate:
    spec:
      version: v1 # version of the Stack.
      replicas: 3
      # optional horizontalPodAutoscaler definition (will create an HPA for the stack).
      horizontalPodAutoscaler:
        minReplicas: 3
        maxReplicas: 10
        metrics:
        - type: Resource
          resource:
            name: cpu
            targetAverageUtilization: 50
      # full Pod template.
      podTemplate:
        spec:
          containers:
          - name: nginx
            image: nginx
            ports:
            - containerPort: 80
              name: ingress
            resources:
              limits:
                cpu: 10m
                memory: 50Mi
              requests:
                cpu: 10m
                memory: 50Mi
```

error message shown:

```
error: error validating "stackset.yaml": error validating data: ValidationError(StackSet.spec.routegroup): unknown field "metadata" in org.zalando.v1.StackSet.spec.routegroup; if you choose to ignore these errors, turn validation off with --validate=false
```

I did a quick check in type definition and [RouteGroupSpec](https://github.com/zalando-incubator/stackset-controller/blob/f88b02083f3fa24da383b157c86291eedda36879/pkg/apis/zalando.org/v1/types.go#L117) did not contain EmbeddedObjectMetaWithAnnotations.
