### ISSUE TITLE
Cannot overwrite rollingUpdate strategy for Stack's Deployment 

### ISSUE THREAD

**Issue by RohanNg** [zalando-incubator/stackset-controller#371]
## Problem

`rollingUpdate` was specified according to StackSet specification (`zkubectl explain stackset.spec.stackTemplate.spec.strategy
`)
```yaml
apiVersion: zalando.org/v1
kind: StackSet
metadata:
  ...
spec:
  ...
  stackTemplate:
    spec:
      ...
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 1
```

The resulting Stack has the right setting:

```yaml
kubectl describe stack <stackname>

...
Strategy:
  Rolling Update:
    Max Surge:        25%
    Max Unavailable:  1
...

```

However, the deployment doesn't get the rollingUpdate value:

```yaml
kubectl describe deploy <deployment-of-the-stack>

...
RollingUpdateStrategy:  1 max unavailable, 5% max surge // still using the default
...
```
