### ISSUE TITLE
custom autoscaling does not work

### ISSUE THREAD

**Issue by szuecs** [zalando-incubator/stackset-controller#64]
I created a custom autoscaling with skipper requests per second like this in my stackset:
```
      horizontalPodAutoscaler:
        minReplicas: 2
        maxReplicas: 10
        metrics:
        - type: Object
          object:
            metricName: requests-per-second
            target:
              apiVersion: extensions/v1beta1
              kind: Ingress
              name: "{{{APPLICATION}}}"
          targetValue: 100
```

The created stack contains a wrong targetValue:
```
  horizontalPodAutoscaler:
    maxReplicas: 10
    metadata:
      creationTimestamp: null
    metrics:
    - object:
        metricName: requests-per-second
        target:
          apiVersion: extensions/v1beta1
          kind: Ingress
          name: sandbox-tokeninfo-bridge
        targetValue: "0"
      type: Object
    minReplicas: 2
```

This is the log I see in stackset-controller:
```
time="2018-10-04T15:45:38Z" level=info msg="Event(v1.ObjectReference{Kind:\"Stack\", Namespace:\"default\", Name:\"sandbox-tokeninfo-bridge-pr-22-3\", UID:\"42a39bcb-c7ea-11e8-bd06-060172d696fe\", APIVersion:\"zalando.org/v1\", ResourceVersion:\"245331352\", FieldPath:\"\"}): type: 'Normal' reason: 'CreateHPA' Creating HPA default/sandbox-tokeninfo-bridge-pr-22-3 for Deployment default/sandbox-tokeninfo-bridge-pr-22-3"
time="2018-10-04T15:45:38Z" level=error msg="Failed to manage Stack default/sandbox-tokeninfo-bridge-pr-22-3: HorizontalPodAutoscaler.autoscaling \"sandbox-tokeninfo-bridge-pr-22-3\" is invalid: spec.metrics[0].object.targetValue: Required value: must specify a positive target value"
```

**Comment by mikkeloscar** [comment]
The problem here is that `targetValue: 100` is not indented enough, it should be under the `object`. We can't really catch these errors with the CRD schema validation unfortunately.

While looking into this I found another issue related to HPAs. this is fixed in #68

**Comment by mikkeloscar** [comment]
> I am not sure if K understand but as far as I see it is indented as you say

It should be indented like this:

```yaml
horizontalPodAutoscaler:
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metricName: requests-per-second
      target:
        apiVersion: extensions/v1beta1
        kind: Ingress
        name: "{{{APPLICATION}}}"
      targetValue: 100 # <- this was not indented enough.
```

Closing as this works as expected.
