### ISSUE TITLE
Missing way to add annotations to deployment

### ISSUE THREAD

**Issue by evangelion1204** [zalando-incubator/stackset-controller#69]
Hi,

I couldn't find a way to add annotations to a deployment. For service, ingress and even pods it's straight forward. The annotation is at Zalando to define a custom log parsers for Scalyr. 
Maybe I just missed the way to achieve it.

**Comment by mikkeloscar** [comment]
That annotation is added at the pod level i.e. the podTemplate part of the spec.

Example:

```yaml
apiVersion: zalando.org/v1
kind: StackSet
metadata:
  name: my-app
spec:
  ingress:
    hosts: [my-app.example.org, alt.name.org]
    backendPort: 80
  stackLifecycle:
    scaledownTTLSeconds: 300
    limit: 5
  stackTemplate:
    spec:
      version: v1
      replicas: 3
      podTemplate:
        metadata:
          annotations:
            kubernetes-log-watcher/scalyr-parser: '[{"container": "nginx", "parser": "my-parser"}]'
        spec:
          containers:
          - name: nginx
            image: nginx
            ports:
            - containerPort: 80
              name: ingress
```
